name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye  # 使用 Debian 11 (Bullseye) 镜像

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up environment
      run: |
        apt-get update
        apt-get install -y python3 python3-pip
        python3 -m pip install --upgrade pip
        
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        pip3 install pyinstaller
        
    - name: Build with PyInstaller
      run: pyinstaller --onefile main.py
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: debian-build
        path: dist/*
